DEPENDS:remove = "clang clang-cross-x86_64"
DEPENDS:append = " clang15 clang15-cross-x86_64"

EXTRA_OECMAKE:remove = "-DIGC_OPTION__LLVM_PREFERRED_VERSION=${LLVMVERSION}"
EXTRA_OECMAKE:append = " -DIGC_OPTION__LLVM_PREFERRED_VERSION=${LLVM15VERSION}"
